version: '3.8'

services:
  # PostgreSQL Database Definition
  database:
    image: postgres:15
    container_name: moja-baza
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: barcelona10
      POSTGRES_DB: Docker
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - moja-mreza

  # Application Definition
  aplikacija:
    image: davidnovak003/zadnja:latest
    container_name: moja-aplikacija
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Formula1Database=Host=database;Database=Docker;Username=postgres;Password=barcelona10
    depends_on:
      - database
    networks:
      - moja-mreza

# Network Definition
networks:
  moja-mreza:
    name: moja-mreza  
    driver: bridge

# Volume Definition for Persistent Data Storage
volumes:
  db_data:
